server:
  port: 8018

ooad:
  ip: 47.103.29.203
  log-api: 2-6-LOG-SERVICE

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.52.88.176:3306/DB2_5?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: user2_5
    password: ooad5
    initial-size: 5
  application:
    name: 1-3-goods-service

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.ooad.good.domain
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full

eureka:
  client:
   serviceUrl:
    defaultZone: http://www.clines.club:2222/eureka/
  instance:
   tatus-page-url: http://${server.address}:${server.port}/swagger-ui.html#/
   instance-id: ${ooad.sererName}:${server.port}
  ## 设置微服务调用地址为IP优先（缺省为false）
   prefer-ip-address: true
  ## 设置IP地址
   ip-address: ${ooad.ip}
  ## 心跳时间，即服务续约间隔时间（缺省为30s）
   lease-renewal-interval-in-seconds: 2
  ## 发呆时间，即服务续约到期时间（缺省为90s
   lease-expiration-duration-in-seconds: 3
  # 服务名称


#eureka:
#  cilent:
#    serviceUrl:
#      defaultZone: http://47.103.29.203:8761/eureka/


comment-api: http://47.103.29.203:8016
footprint-api: http://47.103.29.203:8017
logging:
  level:
    org.springframework.web: info
    root: error
    com.ooad.good.controller: debug
  file:
    path: D:\ooad-project\pressf\good\src\main\resources\log-config:classpath:logback-spring.xml
